#if !canImport(ObjectiveC)
import XCTest

extension BufferedStreamReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BufferedStreamReaderTests = [
        ("testAdvancePositionBeforeCallback", testAdvancePositionBeforeCallback),
        ("testConsume", testConsume),
        ("testConsumeByte", testConsumeByte),
        ("testConsumeNotExpandable", testConsumeNotExpandable),
        ("testConsumeUntil", testConsumeUntil),
        ("testConsumeWhile", testConsumeWhile),
        ("testFeedLessThanReadCount", testFeedLessThanReadCount),
        ("testPeek", testPeek),
        ("testRead", testRead),
        ("testReadByte", testReadByte),
        ("testReadFixedCapacity", testReadFixedCapacity),
        ("testReadLine", testReadLine),
        ("testReadReservingCapacity", testReadReservingCapacity),
        ("testReadUntil", testReadUntil),
        ("testReadWhile", testReadWhile),
        ("testReadWhileUntilEnd", testReadWhileUntilEnd),
    ]
}

extension BufferedStreamTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BufferedStreamTests = [
        ("testBufferedInputStream", testBufferedInputStream),
        ("testBufferedInputStreamDefaultCapacity", testBufferedInputStreamDefaultCapacity),
        ("testBufferedOutputStream", testBufferedOutputStream),
        ("testBufferedOutputStreamDefaultCapacity", testBufferedOutputStreamDefaultCapacity),
        ("testBufferedStream", testBufferedStream),
        ("testBufferedStreamDefaultCapacity", testBufferedStreamDefaultCapacity),
    ]
}

extension BufferedStreamWriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BufferedStreamWriterTests = [
        ("testWriteByte", testWriteByte),
    ]
}

extension ByteStreamTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ByteStreamTests = [
        ("testAdvancePositionBeforeCallback", testAdvancePositionBeforeCallback),
        ("testCopyBytes", testCopyBytes),
        ("testInputStream", testInputStream),
        ("testNumeric", testNumeric),
        ("testOutputStream", testOutputStream),
    ]
}

extension MemoryStreamTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MemoryStreamTests = [
        ("testBuffer", testBuffer),
        ("testCapacity", testCapacity),
        ("testInitialSize", testInitialSize),
        ("testInputStream", testInputStream),
        ("testMemoryStream", testMemoryStream),
        ("testOutputStream", testOutputStream),
        ("testRead", testRead),
        ("testReadEmpty", testReadEmpty),
        ("testReallocate", testReallocate),
        ("testSeek", testSeek),
        ("testTrivial", testTrivial),
        ("testWrite", testWrite),
        ("testWriteEmpty", testWriteEmpty),
    ]
}

extension StreamReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StreamReaderTests = [
        ("testReadLine", testReadLine),
        ("testUntilEnd", testUntilEnd),
        ("testUntilEndAsString", testUntilEndAsString),
    ]
}

extension StreamTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StreamTests = [
        ("testCopyBytes", testCopyBytes),
        ("testInputStream", testInputStream),
        ("testOutputStream", testOutputStream),
        ("testStream", testStream),
    ]
}

extension SubStreamReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubStreamReaderTests = [
        ("testLimitedBy", testLimitedBy),
        ("testSizedBy", testSizedBy),
    ]
}

extension SubStreamWriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubStreamWriterTests = [
        ("testSizedBy", testSizedBy),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BufferedStreamReaderTests.__allTests__BufferedStreamReaderTests),
        testCase(BufferedStreamTests.__allTests__BufferedStreamTests),
        testCase(BufferedStreamWriterTests.__allTests__BufferedStreamWriterTests),
        testCase(ByteStreamTests.__allTests__ByteStreamTests),
        testCase(MemoryStreamTests.__allTests__MemoryStreamTests),
        testCase(StreamReaderTests.__allTests__StreamReaderTests),
        testCase(StreamTests.__allTests__StreamTests),
        testCase(SubStreamReaderTests.__allTests__SubStreamReaderTests),
        testCase(SubStreamWriterTests.__allTests__SubStreamWriterTests),
    ]
}
#endif
